### PR TITLE
Improve message parsing for PythonFlake8

### PR DESCRIPTION
**Pull request by jawshooah**
Use specific rules to distinguish errors from warnings.

`ERROR_REGEX` taken from https://github.com/SublimeLinter/SublimeLinter-flake8.  The file in question has a copyright notice:

```python
#
# linter.py
# Linter for SublimeLinter3, a code checking framework for Sublime Text 3
#
# Written by Aparajita Fishman
# Copyright (c) 2013 Aparajita Fishman
#
# License: MIT
#
```

How do I properly attribute this in code?

### CODE REVIEW

**Comment by jawshooah** [comment]
For reference, the list of errors was specified in SublimeLinter/SublimeLinter-flake8#6.

**Comment by jawshooah** [comment]
If we'd prefer to steer clear of such subjective distinctions, we could simply parse `E` and `F` messages as errors, and `W`, `C`, `N` as warnings.

**Comment by sds** [comment]
I'm not familiar enough with these errors to know how useful/annoying they are, but I would prefer we rely on the tool to indicate error/warning rather than Overcommit making that decision. This way the conversation occurs on the tool itself, not in Overcommit.

Otherwise looks good.

**Comment by jawshooah** [comment]
In that case, I'll go by the `flake8` [documentation](http://flake8.readthedocs.org/en/latest/warnings.html) and parse `Exxx`, `Fxxx` as errors and everything else as warnings.

**Comment by sds** [comment]
Merged in 3342a22.

**Pull request closed without merging**
