### PR TITLE
Add simplecov coverage tool to spec runs

### PR DESCRIPTION
**Pull request by sectioneight**
I'm out of the Ruby game, so this may be the wrong tool, but when
contributing code I like to know that my change is well-tested. I tried
simplecov and it worked nicely. Perhaps this would be useful for others?

Example report: http://sca.ndella.com/overcommit-coverage/index.html#_AllFiles

### CODE REVIEW

**Comment by lencioni** [comment]
We are already using code climate, so it would be nice to hook coverage into that service (and add a badge to the README).

- https://codeclimate.com/tour/test-coverage
- http://docs.codeclimate.com/article/219-setting-up-test-coverage

I think maybe @sds needs to do this.

**Comment by sectioneight** [comment]
Yea I'm not super familiar with the toolchain, but if there's a way we can surface coverage information to developers before stuff gets merged into master, it may help with contributing better code.

**Comment by lencioni** [comment]
Yeah, that's a great point. I think that Code Climate won't comment on PRs, but Coveralls will. https://coveralls.io

**Comment by sds** [comment]
I ended up adding a Coveralls badge in bbf349a9bce00131236219f5639d79444e4fe719.

Usually not a fan of LOC-based coverage stats, but I've set it up to alert if there's a major drop in testing.

Thanks for making the suggestion.

**Comment by lencioni** [comment]
> Usually not a fan of LOC-based coverage stats

Why not?

**Comment by sds** [comment]
It encourages a type of testing that gives you a false sense of security.

Consider the following code:

```ruby
if condition
  puts 'Huzzah'
end
```

With LOC-based testing, I would only need to have a test that exercises `condition` evaluating to `true` in order to get 100% coverage. What never ends up getting tested is the situation where `condition` is `false`.

[Branch coverage](http://en.wikipedia.org/wiki/Code_coverage#Basic_coverage_criteria) (where every edge of the code path is traversed), is a stronger set of criteria for code coverage, but even it isn't perfect. There is also path coverage and prime path coverage which are mostly of interest in academia or when building an airplane. :smile:

**Pull request closed without merging**
