### PR TITLE
Add ESLint pre-commit hook

### LINKED ISSUE #91: Add ESLint pre-commit hook
> ESLint is an open source project originally created by Nicholas C. Zakas in June 2013. Its goal is to provide a pluggable linting utility for JavaScript.

http://eslint.org/

I think this would be a useful hook to have.

### PR DESCRIPTION
**Pull request by jawshooah**
Closes #91.

### CODE REVIEW

**Comment by lencioni** [comment]
This looks great! :+1: Thanks for working on this @jawshooah

**Comment by jawshooah** [comment]
No problem! Would you like me to squash my commits before this is merged?

**Comment by lencioni** [comment]
No, this is fine. I've pushed this to our internal code review tool already so hopefully things will move along quickly now.

**Comment by lencioni** [comment]
This has now been merged.

**Pull request closed without merging**
