### PR TITLE
Add pre-commit hook for ruby-lint

### PR DESCRIPTION
**Pull request by jawshooah**
https://github.com/YorickPeterse/ruby-lint

This linter is still a bit rough around the edges, so disable it by default.

### CODE REVIEW

**Comment by jawshooah** [comment]
Is that a commonly used extension for Ruby files? It isn't included in the Rubocop or Reek hooks.

**Comment by lencioni** [comment]
It is the extension of the config file used by rack-based applications, such as Rails. Probably 99% of the time it will be `config.ru`, so maybe that would be better?

https://github.com/rack/rack/wiki/%28tutorial%29-rackup-howto

**Comment by jawshooah** [comment]
Ah, I see. That change should probably be made in a separate PR, so it can be applied to Reek and Rubocop as well.

**Comment by jawshooah** [comment]
Actually, I need to edit the inclusions for this linter in particular, since it's intended to be used only on Ruby source files (i.e. not `Gemfile`, `Rakefile` or `*.gemspec`).

**Comment by sds** [comment]
Merged in 8a8df547734fe854cd537f76148acd4499be8054. Thanks!

**Pull request closed without merging**
